FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.5

RUN ./bin/elasticsearch-plugin install https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-stempel/analysis-stempel-8.15.5.zip
